version: '3'

services:
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOST=0.0.0.0
